# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#
---
include:
  - board: eyelash_corne_left
    shield: nice_view_gem
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view_gem
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: eyelash_corne_studio_left
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
